# Generated by Django 5.0.2 on 2024-04-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0002_alter_manufacturer_options_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Part Category',
                'verbose_name_plural': 'Part Categories',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('in_stock', models.BooleanField(default=False, verbose_name='In Stock')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('cheapest_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Cheapest Price')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oldtimers.partcategory', verbose_name='Category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['part_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parts/images/%Y/', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='oldtimers.parts', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Part Image',
                'verbose_name_plural': 'Part Images',
                'ordering': ['-created_at', 'part__name'],
            },
        ),
        migrations.CreateModel(
            name='PartFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='parts/datasheet/%Y/', verbose_name='Datasheet')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_files', to='oldtimers.parts', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Part File',
                'verbose_name_plural': 'Part Files',
                'ordering': ['-created_at', 'part__name'],
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('weblink', models.URLField(blank=True, null=True, verbose_name='Web Link')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Number')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sales Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.manufacturer', verbose_name='Distributor')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_distributors', to='oldtimers.parts', verbose_name='Part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
            },
        ),
        migrations.AddField(
            model_name='parts',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oldtimers.storagelocation', verbose_name='Storage Location'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('vehicle_model', models.CharField(max_length=255, verbose_name='Model')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Image')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='datasheets/', verbose_name='Datasheet')),
                ('model_year', models.PositiveIntegerField(default=2024, verbose_name='Model Year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('vehicle_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle Number')),
                ('engine_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Engine')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('name', 'warehouse'), name='unique_storage_location'),
        ),
        migrations.AddConstraint(
            model_name='parts',
            constraint=models.UniqueConstraint(fields=('part_number', 'name', 'manufacturer'), name='unique_old_part_manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='parts',
            constraint=models.UniqueConstraint(fields=('part_number', 'name'), name='unique_old_part'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('name', 'manufacturer'), name='unique_vehicle'),
        ),
    ]
