# Generated by Django 5.0.2 on 2024-04-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldtimers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='cheapest_price',
        ),
    ]
