# Generated by Django 5.0.2 on 2024-02-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electronic', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortmentbox',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='compartment',
            name='assortment_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic.assortmentbox', verbose_name='Assortment Box'),
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='compartment',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic.part', verbose_name='Part'),
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic.partcategory', verbose_name='Category'),
        ),
        migrations.AddConstraint(
            model_name='assortmentbox',
            constraint=models.UniqueConstraint(fields=('name', 'warehouse'), name='unique_assortment_box'),
        ),
        migrations.AddConstraint(
            model_name='compartment',
            constraint=models.UniqueConstraint(fields=('number', 'assortment_box', 'part'), name='unique_compartment'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('name', 'manufacturer'), name='unique_part'),
        ),
    ]
