# Generated by Django 5.0.2 on 2024-02-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assortmentbox',
            options={'ordering': ['name', 'warehouse__name'], 'verbose_name': 'Assortment Box', 'verbose_name_plural': 'Assortment Boxes'},
        ),
        migrations.AlterModelOptions(
            name='compartment',
            options={'ordering': ['assortment_box', 'number'], 'verbose_name': 'Compartment', 'verbose_name_plural': 'Compartments'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name', 'manufacturer__name'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='partcategory',
            options={'ordering': ['name'], 'verbose_name': 'Part Category', 'verbose_name_plural': 'Part Categories'},
        ),
    ]
